### ISSUE TITLE
GCI -RISHABH JAIN

### ISSUE THREAD

**Issue by rishabhjain2807** [Cloud-CV/Fabrik#222] opened 2017-12-29 09:02 UTC
setting up Fabrik on a machine for development requires running a lot of commands.
what we can do is 
 Different containers for Postgres, NodeJS and Django
 Add instructions in README

**Comment by utsavgarg** [comment] 2017-12-31 09:06
Closing as this is not a bug.

**Closed by utsavgarg** 2017-12-31 09:06 UTC
