### ISSUE TITLE
Press button display with and without adding layer.

### ISSUE THREAD

**Issue by Obtin** [Cloud-CV/Fabrik#223] opened 2017-12-29 14:54 UTC
- the expected behaviour
When no layer is added the Press button should indicate its that it is non-functional.
- the observed behaviour
The button appears the same when being functional (layers added) and even when it is not.(no layers added).

Thanks!
when no layer added.
![fabrik1](https://user-images.githubusercontent.com/25207205/34439742-18abd4b0-ecd6-11e7-867b-959556423a5e.png)
after adding layers
![fabrik2](https://user-images.githubusercontent.com/25207205/34439747-20ab28dc-ecd6-11e7-8bec-8228fe25b3f2.png)

**Comment by nu11us** [comment] 2017-12-29 22:37
I'm not sure what the problem is. When clicked on a button, it simply adds itself to the bottom of the network. If there is no layer bottom to be connected, it will not work. Are you suggesting that if it is not working it should be grayed out? If there is desire for that, I can easily edit the script for that. 

**Image Data**, the first layer that you tested, cannot be added to itself, as it has only output. Since there is an output, but no input, the button will not work. If you were to dress **Image Data** then something like **Convolution**, which has both input and output, it will connect.

**Comment by Obtin** [comment] 2017-12-30 03:12
@nu11us, when no layer is added the Press button should act as it is deactivated. 
![2](https://user-images.githubusercontent.com/25207205/34450899-47ffcc46-ed3d-11e7-9361-67a9879f409a.png)

And after adding layers when it is enabled, it may appear like this.
![1](https://user-images.githubusercontent.com/25207205/34450900-4b1733ec-ed3d-11e7-8b48-0eef9c8f843f.png)

**Comment by nu11us** [comment] 2017-12-30 03:41
But what if someone wants to use the layer through dragging? Each button has two main abilities: it attaches to the bottom of the graph when it is clicked, and it is placed when it is dragged and dropped. What you are suggesting would deactivate the button that could still be dragged.

**Comment by Obtin** [comment] 2017-12-30 17:07
I am very sorry @nu11us I did not get you. Please could you explain to me what does the button do when no layers are added and the nothing to work on.
![image](https://user-images.githubusercontent.com/25207205/34456019-f3fe5ea8-edb1-11e7-830c-6ae050c0ba94.png)
Thank you. :-)

**Comment by nu11us** [comment] 2017-12-30 22:25
Sorry about that. I thought you were referring to one of the buttons on the left. The press buttons should be disabled when then are no layers. I thought you meant once a button (i.e. Input Data) was pressed to create a layer. Yeah, *Press ]* and *Press [* should be disabled. Will get to that shorty.

**Comment by nu11us** [comment] 2017-12-30 23:48
Wrote code that disables the press buttons.

**Comment by kapilkd13** [comment] 2018-02-18 12:03
@deshraj @utsavgarg  I guess with https://github.com/Cloud-CV/Fabrik/pull/280 in place we can close this issue.

**Comment by utsavgarg** [comment] 2018-02-23 06:03
@kapilkd13 Yes, thanks.

**Closed by utsavgarg** 2018-02-23 06:03 UTC
