### ISSUE TITLE
Add VQA model in model zoo for Keras

### ISSUE THREAD

**Issue by dexter1691** [Cloud-CV/Fabrik#118] opened 2017-09-28 14:19 UTC
Fabrik can build / visualize very complex multi-modal architectures using Keras. One of the popular tasks for which we should add a model in model zoo is VQA. Here are some examples: 

- Keras JSON files that can directly be imported: https://github.com/avisingh599/visual-qa/tree/master/models
- https://github.com/anantzoid/VQA-Keras-Visual-Question-Answering
- https://github.com/iamaaditya/VQA_Demo

**Comment by souravsingh** [comment] 2017-09-28 16:49
@dexter1691 I am interested in taking a stab at the issue.

**Comment by dexter1691** [comment] 2017-09-28 18:01
Go for it. Thanks! Let us know if you run into issues or need clarifications.

**Comment by prakharchoudhary** [comment] 2017-09-29 20:57
@dexter1691 Thanks for directing us to the links. I tried testing the models by importing the json files on fabrik.cloudcv.org, however the loader keeps rendering and no visualizations seem to appear.

**Comment by prakharchoudhary** [comment] 2017-09-29 21:06
@dexter1691 Upon checking via browser dev tools, the POST api seems to throw a `ValueError`. The json data is valid, thus I believe we have a bug in the api. Should I create a new issue and work on it? 
![json_import](https://user-images.githubusercontent.com/15031548/31036039-25ddd5ba-a588-11e7-9a11-b0c0b48ea85f.png)

**Comment by dexter1691** [comment] 2017-09-29 22:20
Great! Thanks for looking into it. 
This is why having all kinds of models in the model zoo is helpful, since it helps us surface bugs. 
Please go ahead and create and issue and work on it. 

Thanks again for doing an awesome job at this!

**Comment by utsavgarg** [comment] 2017-10-02 03:46
@prakharchoudhary we are currently facing some *version* issues with Keras on our server, it's probably not an issue with the implementation itself. I would recommend you try importing the models on your local machine to get a better idea what the issue is.

**Comment by utsavgarg** [comment] 2017-10-21 09:56
@prakharchoudhary the deployed version is now fixed, you should be able to import json files of keras models.

**Comment by vpn1997** [comment] 2017-11-14 12:18
hey can i contribute to this?

**Comment by vpn1997** [comment] 2017-12-02 06:27
@dexter1691 Hey , i am working on this issue but theres seems to be some problem in importing json file (https://github.com/vpn1997/VQA)

![image](https://user-images.githubusercontent.com/17298412/33512494-ab78e920-d757-11e7-8489-3249634f1b67.png)

**Comment by vpn1997** [comment] 2017-12-02 06:36
Also while trying out some models given in keras documentation,there were few models which were showing error while importing through json and was showing error like
>> 'Sequential' object is not iterable
>> Exception: Cannot import layer of Model type
file keras_app/views/import_json.py.

**Comment by vpn1997** [comment] 2017-12-04 12:16
I have submitted a PR @dexter1691 please check.

**Closed** 2018-01-05 11:15 UTC
Labels: GSOC, starter-project
