### ISSUE TITLE
The layer parameter doesn't displayed.

### ISSUE THREAD

**Issue by GoodLuckDay** [Cloud-CV/Fabrik#155] opened 2017-11-20 07:48 UTC
When I drag and drop any layer, the parameter is shown well.
But if new layer is dragged and dropped, that it doesn't display parameter.
Except for the first layer, the other layers don't show the parameters.

![2017-11-20 16-42-06](https://user-images.githubusercontent.com/29690624/33007414-06ad8570-ce12-11e7-9c6b-e3c9fd1cbfce.png)
----------------------------------------------------------------------------
![2017-11-20 16-42-12](https://user-images.githubusercontent.com/29690624/33007496-53cf513a-ce12-11e7-8cba-5bd40639e652.png)

**Comment by virajprabhu** [comment] 2017-12-05 04:07
Thanks for reporting, @GoodLuckDay!

**Comment by adamstafa** [comment] 2017-12-18 18:21
The problem is in `tooltip.js, line 37`. `disabled` is `false` for every layer but the first one. I'll try to find out why 😄

**Comment by utsavgarg** [comment] 2017-12-19 08:29
Fixed in #196

**Closed by utsavgarg** 2017-12-19 08:29 UTC
Labels: bug
